### ISSUE TITLE
Support dotnet execution tool

### ISSUE THREAD

**Issue by alexdrl** [dsplaisted/strongnamer#17]
Is there any chance to get support in StrongNamer to be executed in dotnet core CLI?

I tried to follow this tutorial to convert it, but without luck.

If you want I can pass you the WIP.

**Comment by Digitalroot** [comment]
I think this is my problem too. I get the following error when trying to build on Ubuntu 16.4.

/[removed]/.nuget/packages/strongnamer/0.0.8/build/StrongNamer.targets(13,5): error MSB4062: The "StrongNamer.AddStrongName" task could not be loaded from the assembly /[removed]/.nuget/packages/strongnamer/0.0.8/build/StrongNamer.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/[removed].csproj]
/[removed]/.nuget/packages/strongnamer/0.0.8/build/StrongNamer.targets(13,5): error MSB4062:  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/[removed].csproj]

In https://github.com/dsplaisted/strongnamer/blob/master/src/StrongNamer/AddStrongName.cs there is usage of Microsoft.Build.Utilities, https://github.com/Microsoft/msbuild/issues/2111 hints at how to change this to use Microsoft.Build.Framework.ITask. 

However it looks like https://github.com/dsplaisted/strongnamer/blob/master/build/Build.tasks is explicitly requiring Microsoft.Build.Utilities.v4.0. which from what I understand is not available on Linux systems. 

For now I am building on a Windows system and deploying to the Linux server, however I would like to be able to build in Linux too. 

I accept that my understanding could be way off, if that is the case, please point me in the right direction.

**Comment by alexdrl** [comment]
This PR adapts the build task to execute on Linux and to bypass the exception that you're hitting. The problem is that this works, but the underlying APIs used in Mono.Cecil (updated to .NET Standard 2.0), does not seem to work in Linux. But, at least, this enables building using dotnet CLI on Windows.
________________________________

**Comment by Digitalroot** [comment]
I've been digging and just found that too. Looks like it is a WIP. See https://github.com/jbevain/cecil/pull/548
I tried porting strongnamer to Standard 2.0 and found the Mono.Cecil issue. Thanks for the PR, I'll give it a shot.

**Comment by ViceIce** [comment]
Any news about this?

**Comment by StefanOssendorf** [comment]
Or statement how the current state is?

**Comment by juanperezADD** [comment]
Any news?

**Comment by Avemey** [comment]
It seems like [cecil](https://github.com/jbevain/cecil/releases/tag/0.11) supports netstandard2.0 out of box. Does it can help solve this issue?

**Comment by dsplaisted** [comment]
Sorry for the long delay on this, and thanks a bunch to @onovotny for the PR that added this support.  The latest package on NuGet.org (0.2.5) should now support building from `dotnet`.
